import {
  Product,
  Category,
  SystemSettings,
  HomePageContent,
  ServiceItem,
  GuideItem,
  Campaign,
  InboxMessage,
  VisitorLog
} from './dbTypes';

export const mapCategoryFromDb = (cat: any): Category => ({
  id: cat.id,
  nameTr: cat.name_tr,
  nameEn: cat.name_en,
  image: cat.image,
  images: cat.images || [],
  status: cat.status,
  displayOrder: cat.display_order,
  descriptionTr: cat.description_tr,
  descriptionEn: cat.description_en,
});

export const mapCategoryToDb = (cat: any) => ({
  id: cat.id,
  name_tr: cat.nameTr,
  name_en: cat.nameEn,
  image: cat.image,
  images: cat.images,
  status: cat.status,
  display_order: cat.displayOrder,
  description_tr: cat.descriptionTr,
  description_en: cat.descriptionEn,
});

export const mapProductFromDb = (p: any): Product => ({
  id: p.id,
  nameTr: p.name_tr,
  nameEn: p.name_en,
  categoryTr: p.category_tr,
  categoryEn: p.category_en,
  categoryId: p.category_id,
  descriptionTr: p.description_tr,
  descriptionEn: p.description_en,
  colors: p.colors || [],
  fabricTypeTr: p.fabric_type_tr,
  fabricTypeEn: p.fabric_type_en,
  priceMultiplier: Number(p.price_multiplier),
  popularity: p.popularity,
  images: p.images || [],
  techSpecsTr: p.tech_specs_tr || [],
  techSpecsEn: p.tech_specs_en || [],
  status: p.status,
  coverImage: p.cover_image,
  displayOrder: p.display_order,
  createdAt: p.created_at,
  updatedAt: p.updated_at,
});

export const mapProductToDb = (p: any) => ({
  id: p.id,
  name_tr: p.nameTr,
  name_en: p.nameEn,
  category_tr: p.categoryTr,
  category_en: p.categoryEn,
  category_id: p.categoryId,
  description_tr: p.descriptionTr,
  description_en: p.descriptionEn,
  colors: p.colors,
  fabric_type_tr: p.fabricTypeTr,
  fabric_type_en: p.fabricTypeEn,
  price_multiplier: p.priceMultiplier,
  popularity: p.popularity,
  images: p.images,
  tech_specs_tr: p.techSpecsTr,
  tech_specs_en: p.techSpecsEn,
  status: p.status,
  cover_image: p.coverImage,
  display_order: p.displayOrder,
  created_at: p.createdAt,
  updated_at: p.updatedAt,
});

export const mapSettingsFromDb = (s: any): SystemSettings => ({
  storeName: s.store_name,
  phone: s.phone,
  email: s.email,
  address: s.address,
  whatsappNumber: s.whatsapp_number,
  googleMapsEmbed: s.google_maps_embed,
  announcementTr: s.announcement_tr,
  announcementEn: s.announcement_en,
  announcementActive: s.announcement_active,
  workingHoursTr: s.working_hours_tr,
  workingHoursEn: s.working_hours_en,
  adminUsername: s.admin_username,
  adminPasswordHash: s.admin_password_hash,
  adminPhone: s.admin_phone,
  adminEmail: s.admin_email,
  googleAdsId: s.google_ads_id || '',
  adsLabelWhatsapp: s.ads_label_whatsapp || '',
  adsLabelContact: s.ads_label_contact || '',
  twoFactorEnabled: !!s.two_factor_enabled,
  twoFactorType: s.two_factor_type || 'both',
  emailSendCount: s.email_send_count || 0,
  lastEmailSendDate: s.last_email_send_date || '',
  shopierUrl: s.shopier_url || '',
  instagramUrl: s.instagram_url || '',
  facebookUrl: s.facebook_url || '',
  linkedinUrl: s.linkedin_url || '',
  campaignInterval: s.campaign_interval || 8,
});

export const mapSettingsToDb = (s: SystemSettings) => ({
  id: 'main_settings',
  store_name: s.storeName,
  phone: s.phone,
  email: s.email,
  address: s.address,
  whatsapp_number: s.whatsappNumber,
  google_maps_embed: s.googleMapsEmbed,
  announcement_tr: s.announcementTr,
  announcement_en: s.announcementEn,
  announcement_active: s.announcementActive,
  working_hours_tr: s.workingHoursTr,
  working_hours_en: s.workingHoursEn,
  admin_username: s.adminUsername,
  admin_password_hash: s.adminPasswordHash,
  admin_phone: s.adminPhone,
  admin_email: s.adminEmail,
  google_ads_id: s.googleAdsId || null,
  ads_label_whatsapp: s.adsLabelWhatsapp || null,
  ads_label_contact: s.adsLabelContact || null,
  two_factor_enabled: !!s.twoFactorEnabled,
  two_factor_type: s.twoFactorType || 'both',
  email_send_count: s.emailSendCount || 0,
  last_email_send_date: s.lastEmailSendDate || '',
  shopier_url: s.shopierUrl || null,
  instagram_url: s.instagramUrl || null,
  facebook_url: s.facebookUrl || null,
  linkedin_url: s.linkedinUrl || null,
  campaign_interval: s.campaignInterval || 8,
});

export const mapHomeContentFromDb = (h: any): HomePageContent => ({
  philosophyTitleTr: h.philosophy_title_tr,
  philosophyTitleEn: h.philosophy_title_en,
  philosophyDescTr: h.philosophy_desc_tr,
  philosophyDescEn: h.philosophy_desc_en,
  craftTitleTr: h.craft_title_tr,
  craftTitleEn: h.craft_title_en,
  craftDescTr: h.craft_desc_tr,
  craftDescEn: h.craft_desc_en,
  collectionsTitleTr: h.collections_title_tr,
  collectionsTitleEn: h.collections_title_en,
  collectionsDescTr: h.collections_desc_tr,
  collectionsDescEn: h.collections_desc_en,
  featuredCategoryIds: h.featured_category_ids || [],
});

export const mapHomeContentToDb = (h: HomePageContent) => ({
  philosophy_title_tr: h.philosophyTitleTr,
  philosophy_title_en: h.philosophyTitleEn,
  philosophy_desc_tr: h.philosophyDescTr,
  philosophy_desc_en: h.philosophyDescEn,
  craft_title_tr: h.craftTitleTr,
  craft_title_en: h.craftTitleEn,
  craft_desc_tr: h.craftDescTr,
  craft_desc_en: h.craftDescEn,
  collections_title_tr: h.collectionsTitleTr,
  collections_title_en: h.collectionsTitleEn,
  collections_desc_tr: h.collectionsDescTr,
  collections_desc_en: h.collectionsDescEn,
  featured_category_ids: h.featuredCategoryIds,
});

export const mapServiceFromDb = (s: any): ServiceItem => ({
  id: s.id,
  titleTr: s.title_tr,
  titleEn: s.title_en,
  descriptionTr: s.description_tr,
  descriptionEn: s.description_en,
  icon: s.icon,
  displayOrder: s.display_order,
  status: s.status,
  image: s.image,
  images: s.images || [],
});

export const mapServiceToDb = (s: ServiceItem) => ({
  id: s.id,
  title_tr: s.titleTr,
  title_en: s.titleEn,
  description_tr: s.descriptionTr,
  description_en: s.descriptionEn,
  icon: s.icon,
  display_order: s.displayOrder,
  status: s.status,
  image: s.image,
  images: s.images,
});

export const mapGuideFromDb = (g: any): GuideItem => ({
  id: g.id,
  titleTr: g.title_tr,
  titleEn: g.title_en,
  summaryTr: g.summary_tr,
  summaryEn: g.summary_en,
  contentTr: g.content_tr,
  contentEn: g.content_en,
  image: g.image,
  date: g.date,
  status: g.status,
  displayOrder: g.display_order,
});

export const mapGuideToDb = (g: GuideItem) => ({
  id: g.id,
  title_tr: g.titleTr,
  title_en: g.titleEn,
  summary_tr: g.summaryTr,
  summary_en: g.summaryEn,
  content_tr: g.contentTr,
  content_en: g.contentEn,
  image: g.image,
  date: g.date,
  status: g.status,
  display_order: g.displayOrder,
});

export const mapCampaignFromDb = (c: any): Campaign => ({
  id: c.id,
  titleTr: c.title_tr,
  titleEn: c.title_en,
  descriptionTr: c.description_tr,
  descriptionEn: c.description_en,
  isActive: c.is_active,
  startDate: c.start_date,
  endDate: c.end_date,
  displayOrder: c.display_order,
});

export const mapCampaignToDb = (c: Campaign) => ({
  id: c.id,
  title_tr: c.titleTr,
  title_en: c.titleEn,
  description_tr: c.descriptionTr,
  description_en: c.descriptionEn,
  is_active: c.isActive,
  start_date: c.startDate,
  end_date: c.endDate,
  display_order: c.displayOrder,
});

export const mapInboxFromDb = (i: any): InboxMessage => ({
  id: i.id,
  type: i.type,
  name: i.name,
  email: i.email,
  phone: i.phone,
  subject: i.subject,
  message: i.message,
  date: i.date,
  isRead: i.is_read,
  isResolved: i.is_resolved,
  isArchived: i.is_archived,
  appointmentDate: i.appointment_date,
  appointmentTime: i.appointment_time,
  address: i.address,
});

export const mapInboxToDb = (i: any) => ({
  id: i.id,
  type: i.type,
  name: i.name,
  email: i.email,
  phone: i.phone,
  subject: i.subject,
  message: i.message,
  is_read: i.isRead,
  is_resolved: i.isResolved,
  is_archived: i.isArchived,
  appointment_date: i.appointmentDate,
  appointment_time: i.appointmentTime,
  address: i.address,
});

export const mapVisitorLogFromDb = (v: any): VisitorLog => ({
  id: v.id,
  city: v.city,
  ip: v.ip,
  userAgent: v.user_agent,
  timestamp: v.timestamp,
  duration: v.duration,
  isBot: v.is_bot,
});

export const mapVisitorLogToDb = (v: VisitorLog) => ({
  id: v.id,
  city: v.city,
  ip: v.ip,
  user_agent: v.userAgent,
  timestamp: v.timestamp,
  duration: v.duration,
  is_bot: v.isBot,
});
